name: CI

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Lint and Test with Node.js ${{ matrix.node }} on ${{ matrix.os }}
    strategy:
      matrix:
        bun:
          - latest
        node:
          - 18
          - 18.18
          - 20
          - 22
          - 24
          - 26
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Setup Bun ${{ matrix.bun }}
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version: ${{ matrix.bun }}

      - name: Install Dependencies
        run: |
          yarn --immutable
          cd test/fixtures/yarn-pnp
          yarn --immutable
          cd ../bun
          bun i --frozen-lockfile

      - name: Downgrade dependencies for Node.js < 20
        if: ${{ matrix.node < 20 }}
        run: yarn add -D concurrently@9 tsdown@0.12.0

      - name: Build and Test
        run: |
          yarn build
          yarn test
        env:
          SYNCKIT_TIMEOUT: 10000

      - name: Lint
        run: yarn lint
        if: ${{ matrix.node >= 20 }}
        env:
          PARSER_NO_WATCH: true

      - name: Benchmark
        run: yarn benchmark

      - name: Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run codacy-coverage-reporter
        # bad Windows -- https://github.com/codacy/codacy-coverage-reporter-action/issues/91
        if: ${{ !github.event.pull_request.head.repo.fork && matrix.os != 'windows-latest' }}
        uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699 # v1.3.0
        continue-on-error: true
        with:
          api-token: ${{ secrets.CODACY_API_TOKEN }}
